# Generated by Django 2.1 on 2018-10-25 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ishow', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='GlobalModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('标题', models.CharField(max_length=255)),
                ('地址', models.CharField(max_length=255)),
                ('邮箱', models.CharField(max_length=255)),
                ('电话', models.CharField(max_length=255)),
                ('手机', models.CharField(max_length=255)),
                ('关于我们', models.CharField(max_length=255)),
                ('微信', models.CharField(max_length=255)),
                ('微博', models.CharField(max_length=255)),
                ('QQ', models.CharField(max_length=255)),
                ('淘宝', models.CharField(max_length=255)),
            ],
        ),
    ]
