# Generated by Django 2.1 on 2018-10-25 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurService',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.BaseModel')),
                ('服务类型', models.CharField(max_length=255)),
                ('服务描述', models.CharField(max_length=255)),
            ],
            bases=('pages.basemodel',),
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.BaseModel')),
                ('口号', models.CharField(max_length=255)),
                ('响亮口号', models.CharField(max_length=255)),
                ('使命', models.CharField(max_length=255)),
            ],
            bases=('pages.basemodel',),
        ),
    ]
