# Generated by Django 2.1 on 2018-10-29 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maps',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.BaseModel')),
                ('分享链接', models.CharField(max_length=255)),
            ],
            bases=('pages.basemodel',),
        ),
        migrations.RenameField(
            model_name='ourguidance',
            old_name='指导描述',
            new_name='业务描述',
        ),
        migrations.RenameField(
            model_name='ourguidance',
            old_name='指导类型',
            new_name='业务类型',
        ),
        migrations.AddField(
            model_name='contacts',
            name='信息描述',
            field=models.CharField(default='11', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='时间',
            field=models.CharField(default='121', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ourguidances',
            name='图标',
            field=models.CharField(default='dsadas', max_length=255),
            preserve_default=False,
        ),
    ]
