# Generated by Django 2.1 on 2018-11-01 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='客户姓名',
            field=models.CharField(default='sss', max_length=255),
            preserve_default=False,
        ),
    ]
