# Generated by Django 2.1 on 2018-10-29 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20181029_1130'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurProductCate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('产品分类', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='ourproduct',
            name='产品分类',
            field=models.CharField(default='1', max_length=255),
            preserve_default=False,
        ),
    ]
