# Generated by Django 2.1 on 2018-10-25 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_ourservice_slider'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choiceus',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.BaseModel')),
                ('选择原因', models.CharField(max_length=255)),
                ('选择原因标题', models.CharField(max_length=255)),
            ],
            bases=('pages.basemodel',),
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.BaseModel')),
            ],
            bases=('pages.basemodel',),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.BaseModel')),
                ('客户头像', models.CharField(max_length=255)),
                ('客户姓名', models.CharField(max_length=255)),
                ('客户职位', models.CharField(max_length=255)),
                ('客户描述', models.CharField(max_length=255)),
            ],
            bases=('pages.basemodel',),
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.BaseModel')),
                ('公司地址', models.CharField(max_length=255)),
                ('电话号码', models.CharField(max_length=255)),
                ('电子邮件', models.CharField(max_length=255)),
            ],
            bases=('pages.basemodel',),
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.BaseModel')),
                ('消息内容', models.CharField(max_length=255)),
                ('消息标题', models.CharField(max_length=255)),
            ],
            bases=('pages.basemodel',),
        ),
        migrations.CreateModel(
            name='OurAdvantage',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.BaseModel')),
                ('优点描述', models.CharField(max_length=255)),
                ('优点分类', models.CharField(max_length=255)),
            ],
            bases=('pages.basemodel',),
        ),
        migrations.CreateModel(
            name='OurGood',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.BaseModel')),
                ('擅长的领域描述', models.CharField(max_length=255)),
                ('擅长的领域分类', models.CharField(max_length=255)),
            ],
            bases=('pages.basemodel',),
        ),
        migrations.CreateModel(
            name='OurGuidance',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.BaseModel')),
                ('指导类型', models.CharField(max_length=255)),
                ('指导描述', models.CharField(max_length=255)),
            ],
            bases=('pages.basemodel',),
        ),
        migrations.CreateModel(
            name='OurGuidances',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.BaseModel')),
                ('服务类型', models.CharField(max_length=255)),
                ('指导描述', models.CharField(max_length=255)),
            ],
            bases=('pages.basemodel',),
        ),
        migrations.CreateModel(
            name='OurPartners',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.BaseModel')),
            ],
            bases=('pages.basemodel',),
        ),
        migrations.CreateModel(
            name='OurProduct',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.BaseModel')),
                ('产品名字', models.CharField(max_length=255)),
                ('产品价格', models.CharField(max_length=255)),
            ],
            bases=('pages.basemodel',),
        ),
        migrations.CreateModel(
            name='OurTeam',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.BaseModel')),
                ('团队人员姓名', models.CharField(max_length=255)),
                ('团队人员职位', models.CharField(max_length=255)),
            ],
            bases=('pages.basemodel',),
        ),
        migrations.AddField(
            model_name='globalmodel',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='ourservice',
            name='口号',
            field=models.CharField(default='q', max_length=255),
            preserve_default=False,
        ),
    ]
