# Generated by Django 2.1 on 2018-11-02 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_clients_客户姓名'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('全名', models.CharField(max_length=255)),
                ('电子邮件', models.CharField(max_length=255)),
                ('网站', models.CharField(max_length=255)),
                ('你的消息', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('称呼', models.CharField(max_length=255)),
                ('电子邮件', models.CharField(max_length=255)),
                ('地址', models.CharField(max_length=255)),
                ('咨询目的', models.CharField(max_length=255)),
                ('咨询产品', models.CharField(max_length=255)),
                ('联系电话', models.CharField(max_length=255)),
            ],
        ),
    ]
